on:
  push:
    branches-ignore:
      - main
jobs:
  deploy-cfts:
    uses: ./.github/workflows/deploy-cfts-to-s3.yaml
    with:
      S3_BUCKET: dev-corelight-cloud-public-templates
      AWS_ROLE: arn:aws:iam::046444305225:role/github-oidc-provider-aws
      AWS_REGION: us-east-2